### ISSUE TITLE
Not working in Visual Studio 2022

### ISSUE THREAD

**Issue by fehmud** [mykolav/must-use-ret-val-fs#1]
Thank you for writing this analyzer! Unfortunately, it is not working here: no errors, no warnings, nothing. Other analyzers are working. What could be wrong?

The package is referenced in the project:

    <ItemGroup>
        <PackageReference Include="MustUseRetVal" Version="0.0.2" />
    </ItemGroup>

I'm using Visual Studio Community 2022.

**Comment by fehmud** [comment]
Sorry, but I had mistakenly added a `MustUseReturnValue` class instead of `MustUseReturnValueAttribute`.

**Comment by mykolav** [comment]
@fehmud 

Glad to hear you figured it out. Happy coding! :)
